// Créez un programme qui remplace les caractères vides par des caractères plein pour représenter le plus grand carré possible sur un plateau. Le plateau sera transmis dans un fichier. La première ligne du fichier contient les informations pour lire la carte : nombre de lignes du plateau, caractères pour “vide”, “obstacle” et “plein”.


// Exemples d’utilisation :
// $> cat plateau
// 9.xo
// ...........................
// ....x......................
// ............x..............
// ...........................
// ....x......................
// ...............x...........
// ...........................
// ......x..............x.....
// ..x.......x................
// $> ruby exo.rb plateau
// .....ooooooo...............
// ....xooooooo...............
// .....ooooooox..............
// .....ooooooo...............
// ....xooooooo...............
// .....ooooooo...x...........
// .....ooooooo...............
// ......x..............x.....
// ..x.......x................

// Vous devez gérer les potentiels problèmes d’arguments, de fichiers, ou de carte invalide.

// Une carte est valide uniquement si : les lignes ont toute la même longueur, il y a au moins une ligne d’une case, les lignes sont séparées d’un retour à la ligne, les caractères présents dans la carte sont uniquement ceux de la première ligne

// En cas de plusieurs solutions, le carré le plus en haut à gauche sera choisi.

///////////////////////////////////////////////////// Pseudo code ////////////////////////////////////////////////////////////////


/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
